// Code generated by "stringer -type=ALUMode"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NOP-0]
	_ = x[AND-1]
	_ = x[OR-2]
	_ = x[NOT-3]
	_ = x[X3_-4]
	_ = x[X2_-5]
	_ = x[X1_-6]
	_ = x[X0_-7]
	_ = x[ADD-8]
	_ = x[SUB-9]
	_ = x[ADC-10]
	_ = x[SBC-11]
	_ = x[NEG-12]
	_ = x[INC-13]
	_ = x[DEC-14]
	_ = x[CMP-15]
}

const _ALUMode_name = "NOPANDORNOTX3_X2_X1_X0_ADDSUBADCSBCNEGINCDECCMP"

var _ALUMode_index = [...]uint8{0, 3, 6, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47}

func (i ALUMode) String() string {
	if i >= ALUMode(len(_ALUMode_index)-1) {
		return "ALUMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ALUMode_name[_ALUMode_index[i]:_ALUMode_index[i+1]]
}
