// Code generated by "stringer -type=ALUMode"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ALUNOP-0]
	_ = x[ALUAND-1]
	_ = x[ALUOR-2]
	_ = x[ALUNOT-3]
	_ = x[X3_-4]
	_ = x[X2_-5]
	_ = x[X1_-6]
	_ = x[X0_-7]
	_ = x[ALUADD-8]
	_ = x[ALUSUB-9]
	_ = x[ALUADC-10]
	_ = x[ALUSBC-11]
	_ = x[ALUNEG-12]
	_ = x[ALUINC-13]
	_ = x[ALUDEC-14]
	_ = x[ALUCMP-15]
}

const _ALUMode_name = "ALUNOPALUANDALUORALUNOTX3_X2_X1_X0_ALUADDALUSUBALUADCALUSBCALUNEGALUINCALUDECALUCMP"

var _ALUMode_index = [...]uint8{0, 6, 12, 17, 23, 26, 29, 32, 35, 41, 47, 53, 59, 65, 71, 77, 83}

func (i ALUMode) String() string {
	if i >= ALUMode(len(_ALUMode_index)-1) {
		return "ALUMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ALUMode_name[_ALUMode_index[i]:_ALUMode_index[i+1]]
}
