// Code generated by "stringer -type=Control"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HLT-2147483648]
	_ = x[AI-1073741824]
	_ = x[AO-536870912]
	_ = x[BI-268435456]
	_ = x[II-134217728]
	_ = x[CIW-67108864]
	_ = x[CIL-33554432]
	_ = x[CIH-16777216]
	_ = x[COW-8388608]
	_ = x[CU-4194304]
	_ = x[CUW-2097152]
	_ = x[MIW-1048576]
	_ = x[MU-524288]
	_ = x[MUW-262144]
	_ = x[RI-131072]
	_ = x[RO-65536]
	_ = x[ROW-32768]
	_ = x[POW-16384]
	_ = x[PU-8192]
	_ = x[PUW-4096]
	_ = x[PD-2048]
	_ = x[PDW-1024]
	_ = x[AU3-512]
	_ = x[AU2-256]
	_ = x[AU1-128]
	_ = x[AU0-64]
	_ = x[FL-32]
	_ = x[EX3-16]
	_ = x[EX2-8]
	_ = x[EX1-4]
	_ = x[EX0-2]
	_ = x[STR-1]
}

const _Control_name = "STREX0EX1EX2EX3FLAU0AU1AU2AU3PDWPDPUWPUPOWROWRORIMUWMUMIWCUWCUCOWCIHCILCIWIIBIAOAIHLT"

var _Control_map = map[Control]string{
	1:          _Control_name[0:3],
	2:          _Control_name[3:6],
	4:          _Control_name[6:9],
	8:          _Control_name[9:12],
	16:         _Control_name[12:15],
	32:         _Control_name[15:17],
	64:         _Control_name[17:20],
	128:        _Control_name[20:23],
	256:        _Control_name[23:26],
	512:        _Control_name[26:29],
	1024:       _Control_name[29:32],
	2048:       _Control_name[32:34],
	4096:       _Control_name[34:37],
	8192:       _Control_name[37:39],
	16384:      _Control_name[39:42],
	32768:      _Control_name[42:45],
	65536:      _Control_name[45:47],
	131072:     _Control_name[47:49],
	262144:     _Control_name[49:52],
	524288:     _Control_name[52:54],
	1048576:    _Control_name[54:57],
	2097152:    _Control_name[57:60],
	4194304:    _Control_name[60:62],
	8388608:    _Control_name[62:65],
	16777216:   _Control_name[65:68],
	33554432:   _Control_name[68:71],
	67108864:   _Control_name[71:74],
	134217728:  _Control_name[74:76],
	268435456:  _Control_name[76:78],
	536870912:  _Control_name[78:80],
	1073741824: _Control_name[80:82],
	2147483648: _Control_name[82:85],
}

func (i Control) String() string {
	if str, ok := _Control_map[i]; ok {
		return str
	}
	return "Control(" + strconv.FormatInt(int64(i), 10) + ")"
}
