// Code generated by "stringer -type=Flag"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OverflowFlagV-1]
	_ = x[NegativeFlagN-2]
	_ = x[CarryFlagC-4]
	_ = x[ZeroFlagZ-8]
	_ = x[InterruptFlagI-16]
	_ = x[ReservedFlag0_-32]
	_ = x[ReservedFlag1_-64]
	_ = x[ReservedFlag2_-128]
}

const (
	_Flag_name_0 = "OverflowFlagVNegativeFlagN"
	_Flag_name_1 = "CarryFlagC"
	_Flag_name_2 = "ZeroFlagZ"
	_Flag_name_3 = "InterruptFlagI"
	_Flag_name_4 = "ReservedFlag0_"
	_Flag_name_5 = "ReservedFlag1_"
	_Flag_name_6 = "ReservedFlag2_"
)

var (
	_Flag_index_0 = [...]uint8{0, 13, 26}
)

func (i Flag) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Flag_name_0[_Flag_index_0[i]:_Flag_index_0[i+1]]
	case i == 4:
		return _Flag_name_1
	case i == 8:
		return _Flag_name_2
	case i == 16:
		return _Flag_name_3
	case i == 32:
		return _Flag_name_4
	case i == 64:
		return _Flag_name_5
	case i == 128:
		return _Flag_name_6
	default:
		return "Flag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
