// Code generated by "stringer -type=OpCode"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NOP-0]
	_ = x[STOA-1]
	_ = x[STOZ-2]
	_ = x[STOM-3]
	_ = x[LODI-4]
	_ = x[LODA-5]
	_ = x[LODZ-6]
	_ = x[LODM-7]
	_ = x[NEG-8]
	_ = x[ASL-9]
	_ = x[ASR-10]
	_ = x[NOT-11]
	_ = x[LSL-12]
	_ = x[LSR-13]
	_ = x[ROL-14]
	_ = x[ROR-15]
	_ = x[ADDI-16]
	_ = x[ADDA-17]
	_ = x[ADDZ-18]
	_ = x[ADDM-19]
	_ = x[SUBI-20]
	_ = x[SUBA-21]
	_ = x[SUBZ-22]
	_ = x[SUBM-23]
	_ = x[ADCI-24]
	_ = x[ADCA-25]
	_ = x[ADCZ-26]
	_ = x[ADCM-27]
	_ = x[SBCI-28]
	_ = x[SBCA-29]
	_ = x[SBCZ-30]
	_ = x[SBCM-31]
	_ = x[ANDI-32]
	_ = x[ANDA-33]
	_ = x[ANDZ-34]
	_ = x[ANDM-35]
	_ = x[ORI-36]
	_ = x[ORA-37]
	_ = x[ORZ-38]
	_ = x[ORM-39]
	_ = x[XORI-40]
	_ = x[XORA-41]
	_ = x[XORZ-42]
	_ = x[XORM-43]
	_ = x[CMPI-44]
	_ = x[CMPA-45]
	_ = x[CMPZ-46]
	_ = x[CMPM-47]
	_ = x[BEQ-48]
	_ = x[BNE-49]
	_ = x[BCS-50]
	_ = x[BCC-51]
	_ = x[BMI-52]
	_ = x[BPL-53]
	_ = x[BVS-54]
	_ = x[BVC-55]
	_ = x[SEI-56]
	_ = x[JMP-57]
	_ = x[JMPZ-58]
	_ = x[JSR-59]
	_ = x[JSRZ-60]
	_ = x[RTS-61]
	_ = x[INT-62]
	_ = x[RTI-63]
	_ = x[CLZ-64]
	_ = x[RSV1-65]
	_ = x[CLC-66]
	_ = x[RSV2-67]
	_ = x[CLN-68]
	_ = x[RSV3-69]
	_ = x[CLV-70]
	_ = x[RSV4-71]
	_ = x[CLI-72]
	_ = x[RSV5-73]
	_ = x[RSV6-74]
	_ = x[RSV7-75]
	_ = x[RSV8-76]
	_ = x[PUSH-77]
	_ = x[POP-78]
	_ = x[HALT-79]
}

const _OpCode_name = "NOPSTOASTOZSTOMLODILODALODZLODMNEGASLASRNOTLSLLSRROLRORADDIADDAADDZADDMSUBISUBASUBZSUBMADCIADCAADCZADCMSBCISBCASBCZSBCMANDIANDAANDZANDMORIORAORZORMXORIXORAXORZXORMCMPICMPACMPZCMPMBEQBNEBCSBCCBMIBPLBVSBVCSEIJMPJMPZJSRJSRZRTSINTRTICLZRSV1CLCRSV2CLNRSV3CLVRSV4CLIRSV5RSV6RSV7RSV8PUSHPOPHALT"

var _OpCode_index = [...]uint16{0, 3, 7, 11, 15, 19, 23, 27, 31, 34, 37, 40, 43, 46, 49, 52, 55, 59, 63, 67, 71, 75, 79, 83, 87, 91, 95, 99, 103, 107, 111, 115, 119, 123, 127, 131, 135, 138, 141, 144, 147, 151, 155, 159, 163, 167, 171, 175, 179, 182, 185, 188, 191, 194, 197, 200, 203, 206, 209, 213, 216, 220, 223, 226, 229, 232, 236, 239, 243, 246, 250, 253, 257, 260, 264, 268, 272, 276, 280, 283, 287}

func (i OpCode) String() string {
	if i >= OpCode(len(_OpCode_index)-1) {
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpCode_name[_OpCode_index[i]:_OpCode_index[i+1]]
}
